package pojo;
// Generated Aug 25, 2019 5:53:18 PM by Hibernate Tools 4.3.1



/**
 * Account generated by hbm2java
 */
public class Account  implements java.io.Serializable {


     private String username;
     private String password;
     private Integer level;

    public Account() {
    }

	
    public Account(String username) {
        this.username = username;
    }
    public Account(String username, String password, Integer level) {
       this.username = username;
       this.password = password;
       this.level = level;
    }
   
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Integer getLevel() {
        return this.level;
    }
    
    public void setLevel(Integer level) {
        this.level = level;
    }




}


