package pojo;
// Generated Aug 25, 2019 4:13:48 PM by Hibernate Tools 4.3.1



/**
 * Monhoc generated by hbm2java
 */
public class Monhoc  implements java.io.Serializable {


     private String maMh;
     private String tenMh;
     private String phongHoc;
     private String monhoccol;

    public Monhoc() {
    }

	
    public Monhoc(String maMh) {
        this.maMh = maMh;
    }
    public Monhoc(String maMh, String tenMh, String phongHoc, String monhoccol) {
       this.maMh = maMh;
       this.tenMh = tenMh;
       this.phongHoc = phongHoc;
       this.monhoccol = monhoccol;
    }
   
    public String getMaMh() {
        return this.maMh;
    }
    
    public void setMaMh(String maMh) {
        this.maMh = maMh;
    }
    public String getTenMh() {
        return this.tenMh;
    }
    
    public void setTenMh(String tenMh) {
        this.tenMh = tenMh;
    }
    public String getPhongHoc() {
        return this.phongHoc;
    }
    
    public void setPhongHoc(String phongHoc) {
        this.phongHoc = phongHoc;
    }
    public String getMonhoccol() {
        return this.monhoccol;
    }
    
    public void setMonhoccol(String monhoccol) {
        this.monhoccol = monhoccol;
    }




}


